# Generated by Django 3.2.8 on 2021-10-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplesdata',
            name='fullname',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
