# Generated by Django 3.2.8 on 2021-10-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_peoplesdata_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplesdata',
            name='Tozihat',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
