# Generated by Django 3.2.9 on 2021-11-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_peoplesdata_tozihat'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplesdata',
            name='mandesincemahegabl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peoplesdata',
            name='moavagemahiyane',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peoplesdata',
            name='ozviyat',
            field=models.IntegerField(default=0),
        ),
    ]
